added test for describe_na_value, and describe_na_value
UBC-MDS/edar pull request #38
Opened 2020-03-05 02:55 UTC by v5y8

closes #21 
closes #22

also updated NAMESPACE and added relevant dependencies

2020-03-06 23:23 UTC, sgauravm requested changes
The code looks concise and neat. Just include defensive coding as it is one of the requirement in this MIlestone.

2020-03-06 23:23 UTC, sgauravm commented on R/eda.R
> +  ret_dataframe <-purrr::map(dataframe, function(x){as.numeric(!is.na(x))})
You can write some defensive code to check for the valid input types. This s one of the requirement of this milestone. Accordingly you can write some test cases to test these exceptions

2020-03-06 23:23 UTC, sgauravm commented on tests/testthat/test-eda.R
> +
Once you complete defensive coding add some test cases for the exceptions thrown for the "defensive coding part"

2020-03-07 01:37 UTC, v5y8 commented
@sgauravm I've added some type checks. please take a look.

2020-03-07 01:44 UTC, sgauravm approved these changes
looks good . YOu can merge now

2020-03-07 01:46 UTC, merged